### ISSUE TITLE
Adapt new branding into the Dashboard

### ISSUE THREAD

**Issue by maemultichain** [edenia/antelope-tools#1109]
**Description and Expected**

There's the Antelope UI Brand toolkit available to use. We need to apply its essence into the Dashboard application.
You can access to this package via Slack >General > Antelope UI Brand Toolkit.

**Tasks**

- [ ] Review the material
- [ ] Prioritize elements to use further
- [ ] Create a re-branding UI proposal for icons and UI (desirable) 
- [ ] Analyze the scope vs opportunity
- [ ] Coordinate with Developer uncharged
