### ISSUE TITLE
Non-compliant improvements and apply feedback

### ISSUE THREAD

**Issue by Torresmorah** [edenia/antelope-tools#1127]
**Epic:**
As a user I would like that when visiting the section of non-compliant producers this one offered a good design of UI/UX to be able to visualize the data correctly, and in a pleasant way.

**Criteria:**
Consider checking the original design for implement the correct spacing and alignment of the new elements in the non-compliant section, and also apply the next feedback given about it.

- The logo isn't displayed in full and the cards must be white. [ See Image 1 ]
- This button in the Rewads distribution section must be align with the title instead of the number. 
   [ See Image 2 ]

_Image 1._ Non-compliant BP's section.

![imagen](https://user-images.githubusercontent.com/66583677/213770314-10ceb0bc-57fa-442f-8512-9d9f5eff9e1b.png)

_Image 2._ Rewards Distribution section.

![imagen](https://user-images.githubusercontent.com/66583677/213771053-08011b8b-6d7a-4615-b175-95b7bd0a0bd4.png)

**Tasks:**

- [x] Apply corrections to the implement design:
   - [x] Set the correct background color of the cards.
   - [x] Align the button of "Show List" in Rewards distribution.
   - [x] Use the correct icon in the sidebar.
- [x] Validate the website of the non-compliant BP.
