### ISSUE TITLE
Show stats about Nodes behavior

### ISSUE THREAD

**Issue by maemultichain** [edenia/antelope-tools#1160]
**Epic:** As a visitor, I'd like to have a new section where stats about the nodes can be shown in a 30 days timeline. 

**Tasks**

- [ ] DB logical model
- [ ] Backend data collection
- [ ] Optimize health check performance
- [ ] Choosing the chart to display data
- [ ] Display data in frontend
- [ ] Internationalization
