### ISSUE TITLE
Improve non compliant BP section

### ISSUE THREAD

**Issue by xavier506** [edenia/antelope-tools#940]
As an end-user, I'd like to see correctly the information about the BPs that aren't follow the compliance within the blockchain networks.

**Acceptance criteria:**

Non compliant BPs are a big problem on EOS. We need to give this information more of spotlight, perhaps even its own section on the main menu. Let's create it and gather:
- Total rewards claimed by BP
- Website
- Votes 
- Account name 
- Last time claimed

**Tasks:**

- [x] Create a UI Draft based on the criteria
- [x] Present a 1. version partners
- [x] Improve based on feedback
- [x]  Share the 2 version to team and expecting approval, *if not correct based on FB.
- [ ] Deploy and set the changes on the Website.
